export const STORE_TYPES = {
    REDUX: 'REDUX',
    PROVIDER: 'PROVIDER'
};

export const FORM_TYPES = {
    SELECT: 'SELECT',
    CHECKBOX: 'CHECKBOX',
    RADIO: 'RADIO',
    INPUT: 'INPUT',
    OPTIONS: 'OPTIONS',
    DATE_PICKER: 'DATE_PICKER',
    DATE_TIME_PICKER: 'DATE_TIME_PICKER',
    TIME_PICKER: 'TIME_PICKER'
};
