import { height, minHeight } from "@mui/system";
import { fadeOut } from "utils/style";

export default {
  contentSx: {
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100%",
    overflow: "hidden",
    background:
      'url("https://dak6ovdfbyw15.cloudfront.net/img/5/panpuri-journey-to-the-peak/main-background.png") no-repeat center center',
    backgroundSize: "100% 100%",
    "& .fadeOut": {
      opacity: "0 !important",
      height: "0 !important",
      visibility: "hidden !important",
      transition: "opacity 1s, height 2s, Visibility 2s !important",
    },
    "& .signature": {
      width: "88%",
      margin: "0 auto",
      opacity: "0",
    },
    "& .fadeIn": {
      opacity: "1 !important",
      transition: "opacity 1.2s",
      transitionDelay: "1.5s",
    },
    "&.zoomInToQuiz1": {
      backgroundSize: "280% 280%",
      backgroundPosition: "center 98%",
      transition: "background-size 7s, background-position 7s",
      transitionDelay: "1s",
    },
    "&.zoomInToCapture": {
      backgroundSize: "285% 285%",
      backgroundPosition: "center 55%",
      transition: "background-size 5.5s, background-position 5.5s",
      transitionDelay: "0s",
    },
    "&.zoomInToQuiz3": {
      backgroundSize: "270% 270%",
      backgroundPosition: "center 31%",
      transition: "background-size 6.5s, background-position 6.5s",
      transitionDelay: "1s",
    },
    "&.zoomInToThePeak": {
      backgroundSize: "300% 300%",
      backgroundPosition: "center 0%",
      transition: "background-size 6.5s, background-position 6.5s",
      transitionDelay: "1s",
    },
    "& .quiz1": {
      width: "100%",
      height: "auto",
      marginTop:
        "min(max(var(--app-height)*0.15, 50px), var(--app-height)*0.1)",
      "& .quiz1-bg": {
        opacity: "0",
        position: "fixed",
        top: "-4%",
        left: "0",
        width: "100%",
        transition: "opacity 2.2s",
      },
      "&.fadeIn": {
        "& .quiz1-bg": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "2.5s !important",
        },
        "& .quiz1-desc1": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "2.5s !important",
        },
        "& .quiz1-desc2": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "4.5s !important",
        },
        "& .quiz1-ans": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "6.5s !important",
          "&.selected": {
            opacity: "1 !important",
            transition: "opacity 1s !important",
            transitionDelay: "0s !important",
          },
          "&.unSelected": {
            opacity: "0.4 !important",
            transition: "opacity 1s !important",
            transitionDelay: "0s !important",
          },
        },
      },
    },
    "& .start-capture": {
      position: "relative",
      marginTop: "min(max(20vh, 100px), 20vh)",
      height: "100%",
      "&.fadeIn": {
        "& .start-capture-desc1": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "1s !important",
        },
        "& .start-capture-desc2": {
          opacity: "1",
          transition: "opacity 2.2s",
          transitionDelay: "3s !important",
        },
        "& .start-capture-camera-container": {
          opacity: "1",
        },
      },
    },
    "& .capture-container": {
      "& .capture-camera-btn": {
        width: "20%",
        margin: "0 auto",
      },
      "&.fadeIn": {
        "& .capture-camera-container": {
          opacity: "1",
        },
      },
    },
    "& .start-capture-desc1": {
      width: "100%",
      opacity: "0",
      margin: "0 auto",
      display: "flex",
    },
    "& .start-capture-desc2": {
      opacity: "0",
      display: "flex",
      width: "83%",
      position: "absolute",
      top: "0",
      left: "50%",
      transform: "translate(-50%, -50%)",
      marginTop: "min(max(23vh, 100px), 23vh)",
    },
    "& .start-capture-camera-container": {
      opacity: "0",
      transition: "opacity 2.2s",
      transitionDelay: "5.5s !important",
      "& .start-capture-camera": {
        width: "25%",
        margin: "0 auto 8% auto",
      },
    },
    "& .fadeOutHidden": {
      animation: `${fadeOut} 2s forwards !important`,
    },
  },
  logoImageSx: {
    width: "30%",
    maxWidth: "300px",
    margin:
      "calc(var(--app-height) * 0.07) auto calc(var(--app-height) * 0.02) auto",
  },
  titleContainerSx: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    margin: "calc(var(--app-height) * 0.19) auto 0 auto",
    "& img": {
      width: "100%",
      marginTop: "1%",
    },
  },
  titleSx: {
    color: "#BD4D31",
    margin: "0 0 10px 0",
  },
  footerSx: {
    display: "flex",
    flexDirection: "column",
    backgroundImage: "var(--footer-url)",
    backgroundSize: "cover",
    position: "absolute",
    bottom: "8%",
    left: "0",
    width: "100%",
    height: "161px",
    paddingBottom: "8px",
    justifyContent: "flex-end",
    alignItems: "center",
    zIndex: "1",
    "& .footer-img": {
      width: "20%",
      maxWidth: "300px",
      cursor: "pointer",
      marginBottom: "5%",
    },
  },
  footerTextSx: {
    display: "flex",
    justifyContent: "center",
    "& img": {
      width: "70%",
    },
  },
  footerNextBtnSx: {
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
    backgroundSize: "cover",
    position: "absolute",
    bottom: "3%",
    left: "0",
    width: "100%",
    "& img": {
      width: "80%",
      margin: "0 auto",
    },
    "& .signature-next-btn": {
      opacity: "0.5",
      transition: "opacity 1.2s !important",
      transitionDelay: "0s !important",
    },
  },
  nextBtnSx: {
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
    backgroundSize: "cover",
    position: "absolute",
    bottom: "6%",
    left: "0",
    width: "100%",
    opacity: "0",
    zIndex: "1",
    "& .swipe-btn": {
      width: "30%",
      margin: "0 auto",
    },
    "&.quiz3-next-btn": {
      margin: "0 auto -10% auto",
      zIndex: "1",
    },
  },
  signatureContainerSx: {
    height: "min(max(76vh, 400px), 80vh)",
    position: "relative",
    display: "flex",
    justifyContent: "center",
    background:
      'url("https://dak6ovdfbyw15.cloudfront.net/img/5/panpuri-journey-to-the-peak/signature-bg.png") no-repeat center center',
    backgroundSize: "contain",
    "& .signature-text": {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -68%)",
      height: "min(max(42vh, 375px), 50vh)",
    },
    "& .signature-bg": {
      position: "absolute",
      top: "0",
      width: "100%",
    },
  },
  signatureCanvasSx: {
    position: "absolute",
    aspectRatio: "450/202",
    height: "min(max(11vh, 124px), 17vh)",
    bottom: "50%",
    left: "50%",
    transform: "translate(-50%, 200%)",
    marginBottom: "min(max(-5vw, -8px), -3.5vw)",
    "& .sigCanvas": {
      height: "100%",
      width: "100%",
      position: "absolute",
      border: "1px solid #B64926",
    },
    "& .restart-svg": {
      width: "6%",
      margin: "5px",
      position: "absolute",
      top: "0",
      left: "0",
    },
    "& .signature-placeholder": {
      position: "absolute",
      width: "40%",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
  },
  quiz1ContainerSx: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "auto",
    "& .quiz1-desc1": {
      width: "90%",
      zIndex: "1",
      opacity: "0",
    },
    "& .quiz1-desc2": {
      width: "80%",
      zIndex: "1",
      opacity: "0",
      marginTop: "24px",
      opacity: "0",
      "&.fadeIn": {
        opacity: "1",
        transitionDelay: "4.5s !important",
      },
    },
  },
  quiz1AnswerSx: {
    width: "100%",
    textAlign: "center",
    marginTop: "50px",
    zIndex: "1",
    "& .quiz1-ans": {
      width: "80%",
      margin: "10px 0",
      opacity: "0",
      transition: "opacity 2.2s",
    },
  },
  captureContainerSx: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    "&.capture-container": {
      opacity: "0",
      transition: "opacity 2.2s",
      transitionDelay: ".5s !important",
      position: "absolute",
      width: "100%",
      height: "100vh",
      overflow: "hidden",
      top: "0",
      left: "0",
      "& .capture-bg": {
        opacity: "0.8",
        width: "100%",
        height: "100%",
        objectFit: "cover",
      },
    },
    "& .scroller": {
      position: "absolute",
      bottom: "50%",
      left: "50%",
      transform: "translate(-50%, 40%)",
      height: "min(max(68vh, 400px), 66vh)",
      aspectRatio: "544/899",
      borderRadius: "20px",
      overflowY: "scroll",
      scrollSnapType: "y mandatory",
      scrollBehavior: "smooth",
      border: "1px solid #000",
      "&.scaleInAndRotate": {
        borderRadius: "0",
        border: "12px solid #fff",
        borderBottom: "40px solid #fff",
        transform: "scale(0.65) rotate(-10deg) translate(-90%, 35%)",
        transition: "transform 2s",
        transitionDelay: "1s",
        overflow: "hidden",
        boxShadow: "0 4px 4px #00000040",
      },
    },
    "& .scroller section": {
      scrollSnapAlign: "start",
      minHeight: "100%",
      position: "relative",
      "&.removeMinHeight": {
        minHeight: "auto",
      },
      "& img": {
        width: "100%",
        display: "block",
      },
      "& .swipe-instru": {
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -30%)",
        width: "100%",
        margin: "0 auto",
        zIndex: "1",
        opacity: "1",
        transition: "opacity 1.2s",
        transitionDelay: "2s !important",
        "&.fadeOut": {
          height: "auto !important",
          visibility: "visible !important",
        },
      },
    },
  },
  captureDescSx: {
    "& .quiz2-desc": {
      width: "80%",
      position: "absolute",
      top: "10%",
      left: "50%",
      transform: "translate(-50%, 0)",
      // opacity: '0',
      transition: "opacity 2.2s",
      transitionDelay: "2.5s !important",
    },
    "& .quiz2-next-btn": {
      width: "25%",
      margin: "0 auto -10% auto",
      opacity: "0",
    },
  },
  quiz2AnswerContainerSx: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "min(max(4%, 20px), 4%)",
    "& .quiz2-ans": {
      width: "80%",
      margin: "5px 0",
      opacity: "0",
      transition: "opacity 1.2s !important",
      transitionDelay: "1.5s !important",
    },
    "&.fadeIn": {
      "& .quiz2-ans": {
        opacity: "1",
        "&.selected": {
          opacity: "1 !important",
          transition: "opacity 1s !important",
          transitionDelay: "0s !important",
        },
        "&.unSelected": {
          opacity: "0.4 !important",
          transition: "opacity 1s !important",
          transitionDelay: "0s !important",
        },
      },
    },
  },
  quiz3ContainerSx: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "calc(var(--app-height) * 0.3 + 5px)",
    "& .quiz3-desc1": {
      width: "100%",
      zIndex: "1",
      opacity: "0",
      margin: "0 auto",
      transition: "opacity 2s",
      transitionDelay: "2s !important",
    },
    "& .quiz3-desc2": {
      width: "55%",
      zIndex: "1",
      opacity: "0",
      transition: "opacity 2s",
      transitionDelay: "4s !important",
    },
    "& .quiz3-ans": {
      width: "15%",
      opacity: "0",
      transition: "opacity 2.2s",
    },
    "&.fadeIn": {
      "& .quiz3-desc1": {
        opacity: "1",
        transitionDelay: "1s !important",
      },
      "& .quiz3-desc2": {
        opacity: "1",
        transitionDelay: "3s !important",
      },
      "& .quiz3-ans": {
        opacity: "1",
        transition: "opacity 2.2s",
        transitionDelay: "4.5s !important",
        "&.selected": {
          opacity: "1 !important",
          transition: "opacity 1s !important",
          transitionDelay: "0s !important",
        },
        "&.unSelected": {
          opacity: "0.4 !important",
          transition: "opacity 1s !important",
          transitionDelay: "0s !important",
        },
      },
    },
    "&.fadeOut": {
      height: "auto !important",
    },
  },
  quiz3DescContainerSx: {
    position: "relative",
    display: "flex",
    width: "min(max(90%, 400px), 100%)",
    "& .quiz3-desc2": {
      position: "absolute",
      top: "60%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
  },
  quiz3AnswerSx: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    textAlign: "center",
    zIndex: "10",
    position: "absolute",
    bottom: "min(max(13vh, 60px), 14vh)",
    "& .quiz3-ans": {
      width: "15%",
      margin: "10px 0",
      opacity: "0",
      transition: "opacity 2.2s",
    },
  },
  peakContainerSx: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "min(max(8vh, 50px), 8vh)",
    "& .peak-title": {
      width: "80%",
      margin: "0 auto",
      zIndex: "1",
      opacity: "0",
    },
    "& .peak-desc": {
      width: "100%",
      zIndex: "1",
      opacity: "0",
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -40%)",
    },
    "& .reflect-btn": {
      width: "80%",
      margin: "0 auto",
      opacity: "0",
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, 65%)",
      zIndex: "1",
    },
    "&.fadeIn": {
      "& .peak-title": {
        opacity: "1",
        transition: "opacity 2.2s !important",
        transitionDelay: "2.5s !important",
      },
      "& .peak-desc": {
        opacity: "1",
        transition: "opacity 2.2s !important",
        transitionDelay: "2.5s !important",
      },
      "& .reflect-btn": {
        opacity: "1",
        transition: "opacity 2.2s !important",
        transitionDelay: "2.5s !important",
      },
    },
  },
  signatureHiddenSx: {
    position: "absolute",
    aspectRatio: "450/202",
    height: "min(max(11vh, 124px), 17vh)",
    zIndex: "-9999",
    "& .sigCanvas": {
      height: "100%",
      width: "100%",
      position: "absolute",
    },
  },
  videoContainerSx: {
    position: "absolute",
    objectFit: "cover",
    zIndex: "99",
    opacity: "0",
    transition: "opacity 1.2s",
    transitionDelay: "0s !important",
    width: "100%",
    height: "100vh",
    "& video": {
      objectFit: "cover",
    },
    "&.fadeOut": {
      height: "100vh !important",
    },
  },
  opacitySx: {
    backgroundColor: "#fff",
    opacity: "0",
    height: "100vh",
    width: "100vw",
    position: "fixed",
    top: "0",
    left: "0",
    "&.fadeIn": {
      opacity: "0.3 !important",
      transition: "opacity 1.2s",
      transitionDelay: "0s !important",
    },
  },
};
