export default {
  stampContentSx: {
    position: "relative",
    width: "30%",
    "& .stamp": {
      width: "100%",
      position: "relative",
    },
    "& .stamp-img": {
      width: "100%",
      padding: "7px",
      position: "absolute",
      right: "0",
      bottom: "3%",
    },
  },
  receivePostcardContentSx: {
    height: "100vh",
    overflow: "hidden",
    background:
      'url("https://dak6ovdfbyw15.cloudfront.net/img/5/panpuri-journey-to-the-peak/postcard-reveive-bg.png") no-repeat center center',
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    width: "100%",
    backgroundSize: "cover",
  },
  maskSx: {
    width: "100%",
    height: "100vh",
    position: "absolute",
    backgroundSize: "cover",
    opacity: "0",
    transition: "opacity 1s ease",
    "&.fadeOut": {
      opacity: "1",
    },
  },
  postcardContainerSx: {
    maxWidth: "90%",
    height: "min(max(57vh, 320px), 65vh)",
    aspectRatio: "436/667",
    top: "53%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "transparent",
    position: "absolute",
    borderRadius: "24px",
    perspective: "1000px",
    "& .flip-box-inner": {
      position: "relative",
      width: "100%",
      height: "100%",
      transition: "transform 0.8s",
      transformStyle: "preserve-3d",
    },
    "& .flip-box-back, .flip-box-front": {
      position: "absolute",
      width: "100%",
      height: "100%",
      WebkitBackfaceVisibility: "hidden",
      backfaceVisibility: "hidden",
    },
    "& .flip-box-front": {
      borderRadius: "50%",
    },
    "& .flip-box-back": {
      background: "#fff",
      transform: "rotateY(180deg)",
      borderRadius: "24px",
      boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    },
    "&.flipped": {
      "& .flip-box-inner": {
        transform: "translateY(-10%) rotateY(180deg)",
      },
    },
    "& img": {
      width: "100%",
      height: "100%",
    },
    "& .logo": {
      width: "30%",
      height: "auto",
      position: "absolute",
      bottom: "3%",
      left: "50%",
      transform: "translateX(-50%)",
    },
    "& .click-icon": {
      width: "45%",
      height: "auto",
      position: "absolute",
      bottom: "-12%",
      left: "50%",
      transform: "translateX(-50%)",
    },
  },
  titleSx: {
    height: "min(max(10vh, 50px), 10vh)",
    marginTop: "7%",
    "& .title": {
      height: "100%",
      width: "auto",
      objectFit: "contain",
    },
  },
  postcardInputSx: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: "80%",
    transform: "translate(-50%, -50%)",
    "& .textarea": {
      textAlign: "center",
      border: "none",
      background: "transparent",
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      fontSize: "1.6em",
      display: "block",
      width: "100%",
      overflow: "hidden",
      resize: "both",
      minHeight: "40px",
      lineHeight: "1.3",
      padding: "10px 0",
      outline: "none",
      whiteSpace: "pre-wrap",
      wordWrap: "break-word",
    },
    '& .textarea[contenteditable="true"]:empty::before': {
      content: "'Write your message'",
      display: "block",
      width: "55%",
      textAlign: "center",
      margin: "0 auto",
    },
  },
  postcardTopDateSx: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px",
    "& .date": {
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      fontSize: "1.2em",
      color: "#BEB7AC",
      whiteSpace: "nowrap",
    },
  },
  postcardBottomSx: {
    display: "flex",
    position: "absolute",
    gap: "10px",
    bottom: "10%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "90%",
    "& .bottom-left-imgs": {
      width: "40%",
      height: "auto",
      objectFit: "contain",
    },
  },
  postcardBottomRightSx: {
    position: "relative",
    width: "56%",
    "& label": {
      fontSize: ".7em",
      position: "absolute",
      top: "2px",
      left: "10px",
      color: "gray",
      fontFamily: "Times New Roman",
      pointerEvents: "none",
      transition: "opacity 0.3s ease",
    },
    "& .textarea-container": {
      position: "relative",
      overflow: "hidden",
      "&:before": {
        position: "absolute",
        content: '"____________________A____________________"',
        zIndex: "-1",
        left: "0",
        top: "0",
        width: "100%",
        color: "#BEB7AC",
        lineHeight: "4ch",
      },
    },
    "& textarea": {
      background: "transparent",
      border: "none",
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      display: "block",
      overflow: "hidden",
      resize: "none",
      minHeight: "7ch",
      lineHeight: "3.5ch",
      borderBottom: "1px solid #BEB7AC",
      outline: "none",
      fontSize: ".75em",
      width: "100%",
      borderRadius: "0",
    },
  },
  footerTextSx: {
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
    backgroundSize: "cover",
    position: "fixed",
    bottom: "8%",
    left: "0",
    width: "100%",
    opacity: "1",
    transition: "opacity 1s ease",
    "& img": {
      width: "75%",
      margin: "5% auto",
    },
    "& .post-box-btn": {
      width: "80%",
      margin: "0 auto",
    },
    "&.fadeOut": {
      opacity: "0",
    },
    "& svg": {
      margin: "0 auto",
    },
  },
  bottomTextSx: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    zIndex: "1",
    position: "fixed",
    bottom: "8%",
    transition: "opacity 1s ease",
    "& .restart": {
      width: "55%",
      height: "auto",
      objectFit: "contain",
      "& svg": {
        width: "100%",
      },
      "& .restart-bg": {
        width: "70%",
        height: "auto",
        position: "absolute",
        top: "0",
        left: "0",
        transform: "translate(13%, 25%)",
        objectFit: "contain",
        zIndex: "-1",
      },
    },
    "& .yes-icon": {
      width: "12%",
      height: "auto",
      objectFit: "contain",
      "& svg": {
        width: "100%",
      },
    },
    "&.fadeOut": {
      opacity: "0",
    },
  },
  fullPageLoadingSx: {
    display: "none",
    position: "fixed",
    width: "100%",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: "100",
    "&.show": {
      display: "flex",
    },
  },
};
