export default {
  writePostcardContentSx: {
    flexDirection: "column",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
    backgroundSize: "cover",
  },
  stampContentSx: {
    position: "relative",
    width: "30%",
    "& .stamp": {
      width: "100%",
      position: "relative",
    },
    "& .stamp-img": {
      width: "100%",
      padding: "9px",
      position: "absolute",
      right: "0",
      bottom: "3%",
    },
  },
  postcardContainerSx: {
    maxWidth: "90%",
    height: "min(max(57vh, 400px), 80vh)",
    aspectRatio: "436/667",
    background: "#FFFCF8",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -55%)",
    position: "absolute",
    borderRadius: "24px",
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
    "& img": {
      width: "100%",
      height: "100%",
    },
    "& .logo": {
      width: "30%",
      height: "auto",
      position: "absolute",
      bottom: "3%",
      left: "50%",
      transform: "translateX(-50%)",
    },
  },
  postcardInputSx: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: "80%",
    transform: "translate(-50%, -50%)",
    "& .textarea": {
      textAlign: "center",
      border: "none",
      background: "transparent",
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      fontSize: "1.6em",
      display: "block",
      width: "100%",
      overflow: "hidden",
      resize: "both",
      minHeight: "40px",
      lineHeight: "1.3",
      padding: "10px 0",
      outline: "none",
    },
    '& .textarea[contenteditable="true"]:empty::before': {
      content: "'Write your message'",
      display: "block",
      width: "55%",
      textAlign: "center",
      margin: "0 auto",
    },
  },
  postcardTopDateSx: {
    position: "absolute",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px",
    width: "100%",
    "& .date": {
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      fontSize: "1.2em",
      color: "#BEB7AC",
      whiteSpace: "nowrap",
    },
  },
  postcardBottomSx: {
    display: "flex",
    position: "absolute",
    gap: "10px",
    bottom: "10%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "90%",
    "& .bottom-left-imgs": {
      width: "40%",
      height: "auto",
      objectFit: "contain",
    },
  },
  postcardBottomRightSx: {
    position: "relative",
    width: "56%",
    "& label": {
      fontSize: "0.7em",
      position: "absolute",
      top: "2px",
      left: "10px",
      color: "gray",
      fontFamily: "Times New Roman",
      pointerEvents: "none",
      transition: "opacity 0.3s ease",
    },
    "& .textarea-container": {
      position: "relative",
      overflow: "hidden",
      "&:before": {
        position: "absolute",
        content: '"________________________________________"',
        zIndex: "-1",
        left: "0",
        top: "0",
        width: "100%",
        color: "#BEB7AC",
        lineHeight: "4ch",
      },
    },
    "& textarea": {
      background: "transparent",
      border: "none",
      fontFamily: "Times New Roman",
      fontStyle: "italic",
      display: "block",
      overflow: "hidden",
      resize: "none",
      minHeight: "7ch",
      lineHeight: "3.5ch",
      borderBottom: "1px solid #BEB7AC",
      outline: "none",
      fontSize: ".75em",
      width: "100%",
      borderRadius: "0",
    },
  },
  footerNextBtnSx: {
    justifyContent: "center",
    display: "flex",
    flexDirection: "column",
    backgroundSize: "cover",
    position: "fixed",
    bottom: "3%",
    left: "0",
    width: "100%",
    "& img": {
      width: "80%",
      margin: "5% auto",
    },
    "& .post-box-btn": {
      width: "20%",
      margin: "0 auto",
    },
    "& .post-box-text": {
      position: "absolute",
      width: "40%",
      margin: "0 auto",
      bottom: "-3%",
      left: "50%",
      transform: "translateX(-50%)",
    },
  },
  maskSx: {
    position: "fixed",
    top: "0",
    left: "0",
    width: "100%",
    height: "100vh",
    background: "rgba(0, 0, 0, 0.5)",
    zIndex: "10",
  },
  sentContainerSx: {
    opacity: "0",
    zIndex: "20",
    "&.fadeIn": {
      opacity: "1",
      transition: "opacity 1s ease",
    },
    "&.hidden": {
      display: "none",
    },
  },
  sentContentSx: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
    zIndex: "30",
    "& .sent-content": {
      height: "min(max(68vh, 400px), 66vh)",
    },
    "& .sent-btn": {
      position: "absolute",
      bottom: "7%",
      height: "min(max(8vh, 100px), 6vh)",
    },
  },
};
